# Generated by Django 3.1.5 on 2021-04-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('date', models.DateField()),
                ('lr_no', models.IntegerField(primary_key=True, serialize=False)),
                ('vehicle_no', models.CharField(db_index=True, max_length=100)),
                ('location', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diesel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rtgs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('cancle', 'Cancle')], default='done', max_length=10)),
                ('firm_name', models.CharField(choices=[('new gandhi roadline', 'New Gandhi Roadline'), ('shri ganesh transport', 'Shri Ganesh Transport')], default='shri ganesh transport', max_length=50)),
            ],
            options={
                'db_table': 'entries',
            },
        ),
    ]
