# Generated by Django 3.1.5 on 2021-03-30 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgt_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='entries',
            table='entries',
        ),
    ]
